name: Build and Deploy
on: 
  push:
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/ci.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Critical for GHCR access
    outputs:
      image_tag: ${{ steps.tag.outputs.git_sha }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          install: true

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Short SHA
        id: tag
        run: echo "git_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and Push with Cache
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mono-assessment:${{ steps.tag.outputs.git_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          builder: ${{ steps.buildx.outputs.name }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yaml
    with:
      image_tag: ${{ needs.build.outputs.image_tag }}
    secrets: inherit
