name: Deploy Infrastructure
on:
  push:
    paths:
      - 'terraform/**'
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Terraform Init
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
        env:
          TF_ACTION_WORKSPACE: default

      - name: Configure AWS Credentials for Spaces
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.SPACES_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SPACES_SECRET_KEY }}
          aws-region: us-east-1
          endpoint-url: https://nyc3.digitaloceanspaces.com

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
