name: Deploy Infrastructure
on:
  push:
    paths:
      - 'terraform/**'
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Terraform Init
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
        env:
          TF_ACTION_WORKSPACE: default

      - name: Configure Spaces
        env:
          SPACES_KEY: ${{ secrets.SPACES_ACCESS_KEY }}
          SPACES_SECRET: ${{ secrets.SPACES_SECRET_KEY }}
        run: |
          aws configure set aws_access_key_id $SPACES_KEY
          aws configure set aws_secret_access_key $SPACES_SECRET
          aws configure set default.region us-east-1
          aws configure set default.s3.endpoint_url https://nyc3.digitaloceanspaces.com

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
